import { IMAGES } from "@/config";

export const SERVICE_PAGES = {
  "transfer-malpensa": {
    image: IMAGES.airports,
    it: {
      metaTitle: "Transfer Malpensa | NCC Milano Aeroporto — FIRST MILANO",
      metaDesc: "Transfer privato NCC da e per Milano Malpensa con autista professionale e Mercedes. Monitoraggio volo, accoglienza con cartello, prezzo concordato in anticipo. Prenota con FIRST MILANO.",
      eyebrow: "Transfer Aeroportuale",
      h1: "Transfer NCC Milano Malpensa",
      intro: "Il modo più comodo e puntuale per raggiungere l'aeroporto di Milano Malpensa (MXP) dal centro di Milano — o per essere accolti all'arrivo. FIRST MILANO organizza transfer privati con vetture Mercedes e autisti professionisti, con monitoraggio del volo e prezzo concordato in anticipo.",
      highlights: [
        "Circa 50 km dal centro di Milano — 50/60 minuti di viaggio",
        "Monitoraggio del volo in tempo reale: in caso di ritardo l'autista ti aspetta",
        "Accoglienza agli arrivi con cartello personalizzato",
        "Prezzo chiaro e concordato prima della partenza, senza sorprese",
        "Disponibile anche per Lago di Como, Svizzera e destinazioni extra-urbane",
        "Vetture Mercedes berlina o van, in base a passeggeri e bagagli",
      ],
      steps: [
        { t: "Prenota", d: "Indica data, ora e numero di volo: ti confermiamo subito la disponibilità con un preventivo." },
        { t: "Viaggia", d: "L'autista arriva in anticipo all'indirizzo concordato e si occupa dei bagagli." },
        { t: "Arriva", d: "Check-in senza stress in aeroporto, o accoglienza diretta agli arrivi al tuo ritorno." },
      ],
      ctaTitle: "Prenota il tuo transfer per Malpensa",
      ctaText: "Richiedi un preventivo gratuito: ti rispondiamo rapidamente con la proposta per il tuo viaggio.",
    },
    en: {
      metaTitle: "Malpensa Airport Transfer | Milan Chauffeur — FIRST MILANO",
      metaDesc: "Private chauffeur transfer to and from Milan Malpensa Airport (MXP) with Mercedes vehicles. Flight tracking, meet & greet, price agreed in advance. Book with FIRST MILANO.",
      eyebrow: "Airport Transfer",
      h1: "Milan Malpensa Chauffeur Transfer",
      intro: "The most comfortable and punctual way to reach Milan Malpensa Airport (MXP) from the city centre — or to be welcomed on arrival. FIRST MILANO arranges private transfers with Mercedes vehicles and professional chauffeurs, with flight tracking and a price agreed in advance.",
      highlights: [
        "About 50 km from central Milan — 50/60 minutes journey time",
        "Real-time flight tracking: if your flight is delayed, your chauffeur waits",
        "Arrivals welcome with a personalised name board",
        "Clear price agreed before departure, no surprises",
        "Also available for Lake Como, Switzerland and out-of-town destinations",
        "Mercedes sedan or van, according to passengers and luggage",
      ],
      steps: [
        { t: "Book", d: "Tell us your date, time and flight number: we confirm availability with a quote right away." },
        { t: "Travel", d: "Your chauffeur arrives early at the agreed address and takes care of your luggage." },
        { t: "Arrive", d: "Stress-free check-in at the airport, or a personal welcome at arrivals on your return." },
      ],
      ctaTitle: "Book your Malpensa transfer",
      ctaText: "Request a free quote: we reply quickly with a tailored proposal for your journey.",
    },
  },
  "transfer-linate": {
    image: IMAGES.airports,
    it: {
      metaTitle: "Transfer Linate | NCC Aeroporto Milano Linate — FIRST MILANO",
      metaDesc: "Transfer privato NCC da e per Milano Linate (LIN) con autista professionale. A 20 minuti dal centro: puntualità, accoglienza agli arrivi e prezzo concordato. FIRST MILANO.",
      eyebrow: "Transfer Aeroportuale",
      h1: "Transfer NCC Milano Linate",
      intro: "Milano Linate (LIN) è l'aeroporto della città: a pochi chilometri dal centro, è lo scalo preferito da chi viaggia per lavoro. FIRST MILANO ti accompagna con vetture Mercedes e autisti professionisti, in orario con il tuo volo.",
      highlights: [
        "Circa 7 km dal centro di Milano — 15/25 minuti di viaggio",
        "Ideale per viaggi business e coincidenze ravvicinate",
        "Monitoraggio del volo e accoglienza agli arrivi con cartello",
        "Prezzo concordato in anticipo, senza sorprese",
        "Possibilità di fermate intermedie o autista a disposizione dopo l'arrivo",
        "Vetture Mercedes berlina o van per ogni esigenza di bagagli",
      ],
      steps: [
        { t: "Prenota", d: "Comunica volo, data e orario: ricevi subito la conferma con il preventivo." },
        { t: "Viaggia", d: "Autista puntuale all'indirizzo concordato, viaggio rapido verso lo scalo cittadino." },
        { t: "Arriva", d: "Discesa direttamente al terminal o accoglienza agli arrivi con cartello." },
      ],
      ctaTitle: "Prenota il tuo transfer per Linate",
      ctaText: "Richiedi un preventivo gratuito: ti rispondiamo rapidamente con la proposta per il tuo viaggio.",
    },
    en: {
      metaTitle: "Linate Airport Transfer | Milan Chauffeur — FIRST MILANO",
      metaDesc: "Private chauffeur transfer to and from Milan Linate Airport (LIN). 20 minutes from the city centre: punctuality, meet & greet and a price agreed in advance. FIRST MILANO.",
      eyebrow: "Airport Transfer",
      h1: "Milan Linate Chauffeur Transfer",
      intro: "Milan Linate (LIN) is the city's airport: just a few kilometres from the centre and the preferred hub for business travel. FIRST MILANO takes you there with Mercedes vehicles and professional chauffeurs, in time with your flight.",
      highlights: [
        "About 7 km from central Milan — 15/25 minutes journey time",
        "Ideal for business travel and tight connections",
        "Flight tracking and arrivals welcome with name board",
        "Price agreed in advance, no surprises",
        "Intermediate stops or chauffeur at disposal available after arrival",
        "Mercedes sedan or van for any luggage needs",
      ],
      steps: [
        { t: "Book", d: "Share your flight, date and time: get an instant confirmation with a quote." },
        { t: "Travel", d: "A punctual chauffeur at the agreed address and a fast ride to the city airport." },
        { t: "Arrive", d: "Drop-off right at the terminal, or a personal welcome at arrivals." },
      ],
      ctaTitle: "Book your Linate transfer",
      ctaText: "Request a free quote: we reply quickly with a tailored proposal for your journey.",
    },
  },
  "transfer-orio-al-serio": {
    image: IMAGES.airports,
    it: {
      metaTitle: "Transfer Orio al Serio | NCC Bergamo Milano — FIRST MILANO",
      metaDesc: "Transfer privato NCC da e per l'aeroporto di Bergamo Orio al Serio (BGY) con autista professionale e Mercedes. Prezzo concordato, monitoraggio volo. FIRST MILANO.",
      eyebrow: "Transfer Aeroportuale",
      h1: "Transfer NCC Orio al Serio (Bergamo)",
      intro: "L'aeroporto di Bergamo Orio al Serio (BGY), scalo di molti voli nazionali e low-cost, dista circa 50 km da Milano. Con FIRST MILANO il viaggio diventa parte della vacanza: autista professionale, vettura Mercedes e prezzo concordato in anticipo.",
      highlights: [
        "Circa 50 km da Milano — 50/60 minuti di viaggio",
        "Perfetto per voli low-cost con orari insoliti, anche notturni su prenotazione",
        "Monitoraggio del volo e accoglienza agli arrivi con cartello",
        "Prezzo chiaro concordato prima della partenza",
        "Ideale per gruppi e famiglie con molti bagagli (Mercedes Classe V)",
        "Disponibile anche per stazioni sciistiche e località turistiche",
      ],
      steps: [
        { t: "Prenota", d: "Indica volo, data e orario: ti confermiamo subito disponibilità e prezzo." },
        { t: "Viaggia", d: "Autista puntuale, viaggio confortevole anche negli orari più scomodi." },
        { t: "Arriva", d: "Arrivo al terminal senza pensieri o accoglienza diretta al tuo rientro." },
      ],
      ctaTitle: "Prenota il tuo transfer per Orio al Serio",
      ctaText: "Richiedi un preventivo gratuito: ti rispondiamo rapidamente con la proposta per il tuo viaggio.",
    },
    en: {
      metaTitle: "Orio al Serio Transfer | Bergamo Milan Chauffeur — FIRST MILANO",
      metaDesc: "Private chauffeur transfer to and from Bergamo Orio al Serio Airport (BGY) with Mercedes vehicles. Price agreed in advance, flight tracking. FIRST MILANO.",
      eyebrow: "Airport Transfer",
      h1: "Orio al Serio (Bergamo) Chauffeur Transfer",
      intro: "Bergamo Orio al Serio Airport (BGY), hub for many national and low-cost flights, is about 50 km from Milan. With FIRST MILANO the journey becomes part of the trip: professional chauffeur, Mercedes vehicle and a price agreed in advance.",
      highlights: [
        "About 50 km from Milan — 50/60 minutes journey time",
        "Perfect for low-cost flights at unusual hours, also at night by reservation",
        "Flight tracking and arrivals welcome with name board",
        "Clear price agreed before departure",
        "Ideal for groups and families with lots of luggage (Mercedes V-Class)",
        "Also available for ski resorts and tourist destinations",
      ],
      steps: [
        { t: "Book", d: "Tell us your flight, date and time: we confirm availability and price right away." },
        { t: "Travel", d: "A punctual chauffeur and a comfortable ride, even at the most inconvenient hours." },
        { t: "Arrive", d: "A carefree arrival at the terminal, or a personal welcome on your return." },
      ],
      ctaTitle: "Book your Orio al Serio transfer",
      ctaText: "Request a free quote: we reply quickly with a tailored proposal for your journey.",
    },
  },
  "autista-a-disposizione": {
    image: IMAGES.fleetSedan,
    it: {
      metaTitle: "Autista a Disposizione Milano | NCC a Ore — FIRST MILANO",
      metaDesc: "Autista privato a disposizione a Milano per ore o giornate intere: shopping, meeting, eventi e serate. Vettura Mercedes con conducente sempre pronto. FIRST MILANO.",
      eyebrow: "Servizio a Ore",
      h1: "Autista a Disposizione a Milano",
      intro: "Una vettura Mercedes con autista professionale sempre al tuo fianco: per una giornata di shopping in Quadrilatero, una serie di meeting in città, una serata a teatro o un evento importante. Con FIRST MILANO l'autista ti aspetta dove e quando vuoi.",
      highlights: [
        "Disponibile per alcune ore, l'intera giornata o più giorni",
        "Itinerario completamente flessibile, modificabile in tempo reale",
        "L'autista ti attende a ogni tappa: zero attese, zero parcheggi da cercare",
        "Massima discrezione e riservatezza durante tutto il servizio",
        "Ideale per shopping, meeting, visite mediche, cerimonie e serate",
        "Berlina Mercedes o van Classe V in base alle esigenze",
      ],
      steps: [
        { t: "Raccontaci la giornata", d: "Indicaci durata e tappe indicative: prepariamo un preventivo su misura." },
        { t: "L'autista è tuo", d: "Vettura e conducente a tua completa disposizione per tutto il periodo." },
        { t: "Cambia programma liberamente", d: "Imprevisti o nuove tappe? L'autista si adatta in tempo reale." },
      ],
      ctaTitle: "Richiedi il tuo autista a disposizione",
      ctaText: "Raccontaci la tua giornata: ti rispondiamo con una proposta personalizzata.",
    },
    en: {
      metaTitle: "Hourly Chauffeur Milan | Private Driver Hire — FIRST MILANO",
      metaDesc: "Private chauffeur at your disposal in Milan by the hour or for full days: shopping, meetings, events and evenings out. Mercedes vehicle with driver always ready. FIRST MILANO.",
      eyebrow: "Hourly Service",
      h1: "Chauffeur at Disposal in Milan",
      intro: "A Mercedes vehicle with a professional chauffeur always by your side: for a day of shopping in the Quadrilatero, a series of meetings across the city, a night at the theatre or an important event. With FIRST MILANO your chauffeur waits wherever and whenever you want.",
      highlights: [
        "Available for a few hours, a full day or several days",
        "Fully flexible itinerary, adjustable in real time",
        "Your chauffeur waits at every stop: no waiting, no parking hassle",
        "Complete discretion and confidentiality throughout the service",
        "Ideal for shopping, meetings, medical visits, ceremonies and evenings",
        "Mercedes sedan or V-Class van according to your needs",
      ],
      steps: [
        { t: "Tell us about your day", d: "Share the duration and indicative stops: we prepare a tailored quote." },
        { t: "The chauffeur is yours", d: "Vehicle and driver entirely at your disposal for the whole period." },
        { t: "Change plans freely", d: "New stops or last-minute changes? Your chauffeur adapts in real time." },
      ],
      ctaTitle: "Request your chauffeur at disposal",
      ctaText: "Tell us about your day: we will reply with a personalised proposal.",
    },
  },
  "eventi-fashion-week": {
    image: IMAGES.fleetVan,
    it: {
      metaTitle: "NCC Eventi e Fashion Week Milano — FIRST MILANO",
      metaDesc: "Servizio NCC per eventi, fiere e Milano Fashion Week: transfer per ospiti, delegazioni e VIP con Mercedes e autisti professionisti. Discrezione e puntualità. FIRST MILANO.",
      eyebrow: "Eventi & Fashion",
      h1: "NCC per Eventi e Milano Fashion Week",
      intro: "Durante la Milano Fashion Week, le fiere e i grandi eventi, muoversi in città diventa una sfida. FIRST MILANO coordina transfer e autisti a disposizione per ospiti, delegazioni e clienti VIP, con la puntualità e la discrezione che queste occasioni richiedono.",
      highlights: [
        "Transfer per ospiti e delegazioni durante Fashion Week, Salone del Mobile e fiere",
        "Coordinamento di più vetture per eventi e cerimonie",
        "Autista a disposizione per tutta la durata dell'evento",
        "Massima riservatezza per ospiti pubblici e clienti VIP",
        "Vetture Mercedes berlina e van per singoli o gruppi",
        "Su richiesta, servizio di protezione personale qualificato",
      ],
      steps: [
        { t: "Pianifichiamo insieme", d: "Date, orari, tappe e numero di ospiti: costruiamo il piano dei trasporti." },
        { t: "Coordinamento", d: "Vetture e autisti assegnati, con referente dedicato per l'evento." },
        { t: "L'evento scorre", d: "Ospiti sempre puntuali e assistiti, dall'arrivo alla fine della serata." },
      ],
      ctaTitle: "Organizza i transfer per il tuo evento",
      ctaText: "Raccontaci l'evento: ti rispondiamo con una proposta completa e personalizzata.",
    },
    en: {
      metaTitle: "Chauffeur for Events & Milan Fashion Week — FIRST MILANO",
      metaDesc: "Chauffeur service for events, trade fairs and Milan Fashion Week: transfers for guests, delegations and VIPs with Mercedes and professional chauffeurs. FIRST MILANO.",
      eyebrow: "Events & Fashion",
      h1: "Chauffeur Service for Events & Milan Fashion Week",
      intro: "During Milan Fashion Week, trade fairs and major events, moving around the city becomes a challenge. FIRST MILANO coordinates transfers and chauffeurs at disposal for guests, delegations and VIP clients, with the punctuality and discretion these occasions demand.",
      highlights: [
        "Transfers for guests and delegations during Fashion Week, Salone del Mobile and trade fairs",
        "Coordination of multiple vehicles for events and ceremonies",
        "Chauffeur at disposal for the entire duration of the event",
        "Complete confidentiality for public figures and VIP clients",
        "Mercedes sedans and vans for individuals or groups",
        "On request, qualified personal protection service",
      ],
      steps: [
        { t: "We plan together", d: "Dates, times, stops and number of guests: we build the transport plan." },
        { t: "Coordination", d: "Vehicles and chauffeurs assigned, with a dedicated contact for your event." },
        { t: "The event flows", d: "Guests always on time and looked after, from arrival to the end of the evening." },
      ],
      ctaTitle: "Organise transfers for your event",
      ctaText: "Tell us about your event: we will reply with a complete, tailored proposal.",
    },
  },
};
