import { IMAGES } from "@/config";

export const SERVICE_PAGES = {
  "transfer-malpensa": {
    image: IMAGES.airports,
    it: {
      metaTitle: "NCC Milano Malpensa | Transfer Privato con Autista — FIRST MILANO",
      metaDesc: "Transfer privato NCC da e per Milano Malpensa con autista professionale e Mercedes. Monitoraggio volo, accoglienza con cartello, prezzo concordato in anticipo. Prenota con FIRST MILANO.",
      eyebrow: "Transfer Aeroportuale",
      h1: "NCC Milano Malpensa – Transfer Privato con Autista",
      intro: "Il modo più comodo e puntuale per raggiungere l'aeroporto di Milano Malpensa (MXP) dal centro di Milano — o per essere accolti all'arrivo. FIRST MILANO organizza transfer privati con vetture Mercedes e autisti professionisti, con monitoraggio del volo e prezzo concordato in anticipo.",
      highlights: [
        "Circa 50 km dal centro di Milano — 50/60 minuti di viaggio",
        "Monitoraggio del volo in tempo reale: in caso di ritardo l'autista ti aspetta",
        "Accoglienza agli arrivi con cartello personalizzato",
        "Prezzo concordato prima del servizio, con condizioni definite in anticipo",
        "Disponibile anche per Lago di Como, Svizzera e destinazioni extra-urbane",
        "Vetture Mercedes berlina o van, in base a passeggeri e bagagli",
      ],
      steps: [
        { t: "Prenota", d: "Indica data, ora e numero di volo: ti confermiamo rapidamente la disponibilità con un preventivo." },
        { t: "Viaggia", d: "L'autista arriva in anticipo all'indirizzo concordato e si occupa dei bagagli." },
        { t: "Arriva", d: "Check-in senza stress in aeroporto, o accoglienza diretta agli arrivi al tuo ritorno." },
      ],
      sections: [
        { t: "Accoglienza in aeroporto", d: "All'arrivo a Malpensa trovi l'autista ad attenderti nell'area arrivi con un cartello con il tuo nome. Dopo il ritiro bagagli ti accompagniamo direttamente alla vettura per partire verso la tua destinazione." },
        { t: "Monitoraggio del volo e ritardi", d: "Comunicaci il numero del volo in fase di prenotazione: seguiamo l'atterraggio in tempo reale e adattiamo l'orario di accoglienza. In caso di ritardo, l'autista ti aspetta senza che tu debba fare nulla." },
        { t: "Dove incontri l'autista", d: "Il punto d'incontro è nell'area arrivi del tuo terminal (Malpensa T1 o T2), subito dopo l'uscita dalla zona ritiro bagagli. Prima del viaggio ricevi tutti i dettagli e il recapito dell'autista." },
        { t: "Transfer aeroporto → Milano e Milano → aeroporto", d: "Effettuiamo entrambe le direzioni: accompagnamento alla partenza con arrivo in anticipo all'indirizzo concordato, e accoglienza agli arrivi al tuo rientro. Disponibile a qualsiasi ora, su prenotazione." },
        { t: "Famiglie e gruppi", d: "Per famiglie e piccoli gruppi è disponibile il van Mercedes Classe V, fino a 7 passeggeri con bagagli. Segnala nelle note eventuali esigenze particolari, come seggiolini o attrezzature." },
        { t: "Business travel", d: "Per chi viaggia per lavoro: puntualità, riservatezza e possibilità di autista a disposizione dopo l'arrivo, per meeting e appuntamenti in città senza pensieri." },
        { t: "Bagagli", d: "La berlina è ideale per 1–3 passeggeri con bagagli standard. Con bagagli voluminosi o attrezzature sportive (sci, golf) consigliamo la Classe V: indica il numero di bagagli nel modulo e ti confermeremo la vettura più adatta." },
      ],
      faqs: [
        { q: "Dove trovo l'autista in aeroporto?", a: "Nell'area arrivi del tuo terminal (Malpensa T1 o T2), subito dopo il ritiro bagagli, con un cartello con il tuo nome. Prima del viaggio ricevi tutti i dettagli del punto d'incontro." },
        { q: "Cosa succede se il mio volo è in ritardo?", a: "Monitoriamo il volo in tempo reale: adeguiamo l'orario di accoglienza in base all'andamento del volo e l'autista ti aspetta all'uscita degli arrivi." },
        { q: "Posso prenotare per più passeggeri?", a: "Sì. La berlina Mercedes è ideale per 1–3 passeggeri; per gruppi fino a 7 passeggeri è disponibile il van Mercedes Classe V. Indica il numero di passeggeri nel modulo di richiesta." },
        { q: "Viaggio con molti bagagli: quale vettura devo richiedere?", a: "Con bagagli voluminosi o attrezzature sportive consigliamo la Classe V, che offre ampio spazio. Segnala il numero di bagagli nella richiesta: ti confermeremo la vettura più adatta." },
        { q: "Quanto prima è consigliabile prenotare?", a: "Il servizio è su prenotazione: ti consigliamo di inviare la richiesta appena conosci data e orario del volo. Per esigenze dell'ultimo minuto scrivici su WhatsApp: faremo il possibile per aiutarti." },
      ],
      ctaTitle: "Prenota il tuo transfer per Malpensa",
      ctaText: "Richiedi un preventivo gratuito: ti rispondiamo rapidamente con la proposta per il tuo viaggio.",
    },
    en: {
      metaTitle: "Malpensa Airport Transfer | Milan Private Chauffeur — FIRST MILANO",
      metaDesc: "Private chauffeur transfer to and from Milan Malpensa Airport (MXP) with Mercedes vehicles. Flight tracking, meet & greet, price agreed in advance. Book with FIRST MILANO.",
      eyebrow: "Airport Transfer",
      h1: "Malpensa Airport Private Transfer – Milan Chauffeur Service",
      intro: "The most comfortable and punctual way to reach Milan Malpensa Airport (MXP) from the city centre — or to be welcomed on arrival. FIRST MILANO arranges private transfers with Mercedes vehicles and professional chauffeurs, with flight tracking and a price agreed in advance.",
      highlights: [
        "About 50 km from central Milan — 50/60 minutes journey time",
        "Real-time flight tracking: if your flight is delayed, your chauffeur waits",
        "Arrivals welcome with a personalised name board",
        "Price agreed before the service, with terms defined in advance",
        "Also available for Lake Como, Switzerland and out-of-town destinations",
        "Mercedes sedan or van, according to passengers and luggage",
      ],
      steps: [
        { t: "Book", d: "Tell us your date, time and flight number: we confirm availability with a tailored quote." },
        { t: "Travel", d: "Your chauffeur arrives early at the agreed address and takes care of your luggage." },
        { t: "Arrive", d: "Stress-free check-in at the airport, or a personal welcome at arrivals on your return." },
      ],
      sections: [
        { t: "Meet & greet at the airport", d: "On arrival at Malpensa your chauffeur is waiting in the arrivals hall holding a board with your name. After baggage claim, your chauffeur accompanies you directly to the vehicle for the journey to your destination." },
        { t: "Flight tracking and delays", d: "Share your flight number when booking: we follow the landing in real time and adjust the pick-up time. If your flight is delayed, your chauffeur simply waits for you." },
        { t: "Where you meet your chauffeur", d: "The meeting point is in the arrivals area of your terminal (Malpensa T1 or T2), just after the baggage claim exit. Before the journey you receive all the details and your chauffeur's contact." },
        { t: "Airport → Milan and Milan → airport", d: "We run both directions: drop-off for your departure with the chauffeur arriving early at the agreed address, and a personal welcome at arrivals on your return. Available at any hour, by reservation." },
        { t: "Families and groups", d: "For families and small groups the Mercedes V-Class van is available, seating up to 7 passengers with luggage. Mention any special needs in the notes of your request." },
        { t: "Business travel", d: "For business travellers: punctuality, confidentiality and the option of a chauffeur at disposal after arrival, for meetings and appointments across the city." },
        { t: "Luggage", d: "The sedan is ideal for 1–3 passengers with standard luggage. With bulky luggage or sports equipment (ski, golf) we recommend the V-Class: tell us how many bags you have and we will confirm the most suitable vehicle." },
      ],
      faqs: [
        { q: "Where do I find my chauffeur at the airport?", a: "In the arrivals area of your terminal (Malpensa T1 or T2), right after baggage claim, holding a board with your name. Before the journey you receive all meeting point details." },
        { q: "What happens if my flight is delayed?", a: "We track your flight in real time: we adjust the welcome time based on the flight status and your chauffeur waits for you at the arrivals exit." },
        { q: "Can I book for several passengers?", a: "Yes. The Mercedes sedan is ideal for 1–3 passengers; for groups of up to 7 the Mercedes V-Class van is available. Just indicate the number of passengers in the request form." },
        { q: "I travel with a lot of luggage: which vehicle should I request?", a: "With bulky luggage or sports equipment we recommend the V-Class, which offers generous space. Tell us the number of bags in your request and we will confirm the best vehicle." },
        { q: "How far in advance should I book?", a: "The service works by reservation: we suggest sending your request as soon as you know your flight date and time. For last-minute needs, message us on WhatsApp and we will do our best to help." },
      ],
      ctaTitle: "Book your Malpensa transfer",
      ctaText: "Request a free quote: we reply quickly with a tailored proposal for your journey.",
    },
  },
  "transfer-linate": {
    image: IMAGES.airports,
    it: {
      metaTitle: "Transfer Linate | NCC Aeroporto Milano Linate — FIRST MILANO",
      metaDesc: "Transfer privato NCC da e per Milano Linate (LIN) con autista professionale. A 20 minuti dal centro: puntualità, accoglienza agli arrivi e prezzo concordato. FIRST MILANO.",
      eyebrow: "Transfer Aeroportuale",
      h1: "NCC Milano Linate – Transfer Privato con Autista",
      intro: "Milano Linate (LIN) è l'aeroporto della città: a pochi chilometri dal centro, è lo scalo preferito da chi viaggia per lavoro. FIRST MILANO ti accompagna con vetture Mercedes e autisti professionisti, in orario con il tuo volo.",
      highlights: [
        "Circa 7 km dal centro di Milano — 15/25 minuti di viaggio",
        "Ideale per viaggi business e coincidenze ravvicinate",
        "Monitoraggio del volo e accoglienza agli arrivi con cartello",
        "Prezzo concordato prima del servizio, con condizioni definite in anticipo",
        "Possibilità di fermate intermedie o autista a disposizione dopo l'arrivo",
        "Vetture Mercedes berlina o van per ogni esigenza di bagagli",
      ],
      steps: [
        { t: "Prenota", d: "Comunica volo, data e orario: ricevi la conferma con il preventivo." },
        { t: "Viaggia", d: "Autista puntuale all'indirizzo concordato, viaggio rapido verso lo scalo cittadino." },
        { t: "Arriva", d: "Discesa direttamente al terminal o accoglienza agli arrivi con cartello." },
      ],
      sections: [
        { t: "Accoglienza in aeroporto", d: "L'autista ti attende nell'area arrivi di Linate con un cartello con il tuo nome e ti accompagna alla vettura, parcheggiata a pochi passi. In pochi minuti sei in viaggio verso il centro." },
        { t: "Monitoraggio del volo e ritardi", d: "Seguiamo l'andamento del tuo volo: in caso di ritardo o anticipo, adeguiamo l'orario di accoglienza in base all'andamento del volo. Non devi avvisarci, pensiamo a tutto noi." },
        { t: "Dove incontri l'autista", d: "Il punto d'incontro è nell'area arrivi del terminal, subito dopo il ritiro bagagli. Prima del viaggio ricevi i dettagli del punto d'incontro e il recapito dell'autista." },
        { t: "Transfer aeroporto → Milano e Milano → aeroporto", d: "Servizio in entrambe le direzioni: per la partenza l'autista arriva in anticipo all'indirizzo concordato e calcola i tempi in base al volo; al rientro ti aspettiamo agli arrivi." },
        { t: "Business travel", d: "Linate è lo scalo del business milanese: offriamo un servizio attento a puntualità e riservatezza e, se serve, un autista a disposizione per la giornata di meeting dopo l'atterraggio." },
        { t: "Famiglie, gruppi e bagagli", d: "Per famiglie e piccoli gruppi fino a 7 passeggeri è disponibile il van Mercedes Classe V, con ampio spazio per i bagagli. Indica passeggeri e bagagli nel modulo: ti confermeremo la vettura ideale." },
      ],
      faqs: [
        { q: "Dove trovo l'autista a Linate?", a: "Nell'area arrivi del terminal, subito dopo il ritiro bagagli, con un cartello con il tuo nome. Prima del viaggio ricevi tutti i dettagli del punto d'incontro." },
        { q: "Cosa succede se il mio volo è in ritardo?", a: "Monitoriamo il volo in tempo reale e adeguiamo l'orario di accoglienza: l'autista ti aspetta agli arrivi." },
        { q: "Quanto dura il transfer da Linate al centro?", a: "Linate dista circa 7 km dal centro di Milano: il viaggio dura normalmente 15–25 minuti, in base al traffico e alla destinazione esatta." },
        { q: "Posso prenotare per più passeggeri o con molti bagagli?", a: "Sì. La berlina è ideale per 1–3 passeggeri; il van Classe V accoglie fino a 7 passeggeri con bagagli voluminosi. Indica le tue esigenze nel modulo di richiesta." },
        { q: "Quanto prima è consigliabile prenotare?", a: "Il servizio è su prenotazione: invia la richiesta appena conosci i dettagli del volo. Per l'ultimo minuto, scrivici su WhatsApp e faremo il possibile per aiutarti." },
      ],
      ctaTitle: "Prenota il tuo transfer per Linate",
      ctaText: "Richiedi un preventivo gratuito: ti rispondiamo rapidamente con la proposta per il tuo viaggio.",
    },
    en: {
      metaTitle: "Linate Airport Transfer | Milan Chauffeur — FIRST MILANO",
      metaDesc: "Private chauffeur transfer to and from Milan Linate Airport (LIN). 20 minutes from the city centre: punctuality, meet & greet and a price agreed in advance. FIRST MILANO.",
      eyebrow: "Airport Transfer",
      h1: "Milan Linate Airport Transfer – Private Chauffeur Service",
      intro: "Milan Linate (LIN) is the city's airport: just a few kilometres from the centre and the preferred hub for business travel. FIRST MILANO takes you there with Mercedes vehicles and professional chauffeurs, in time with your flight.",
      highlights: [
        "About 7 km from central Milan — 15/25 minutes journey time",
        "Ideal for business travel and tight connections",
        "Flight tracking and arrivals welcome with name board",
        "Price agreed before the service, with terms defined in advance",
        "Intermediate stops or chauffeur at disposal available after arrival",
        "Mercedes sedan or van for any luggage needs",
      ],
      steps: [
        { t: "Book", d: "Share your flight, date and time: get an instant confirmation with a quote." },
        { t: "Travel", d: "A punctual chauffeur at the agreed address and a fast ride to the city airport." },
        { t: "Arrive", d: "Drop-off right at the terminal, or a personal welcome at arrivals." },
      ],
      sections: [
        { t: "Meet & greet at the airport", d: "Your chauffeur waits for you in the Linate arrivals hall with a board bearing your name and walks you to the vehicle, parked just steps away. Within minutes you are on your way to the city centre." },
        { t: "Flight tracking and delays", d: "We follow your flight: in case of delay or early landing, we adjust the welcome time based on the flight status. You do not need to warn us — we take care of everything." },
        { t: "Where you meet your chauffeur", d: "The meeting point is in the terminal arrivals area, just after baggage claim. Before the journey you receive the meeting point details and your chauffeur's contact." },
        { t: "Airport → Milan and Milan → airport", d: "Service in both directions: for departures the chauffeur arrives early at the agreed address and plans the timing around your flight; on your return we wait for you at arrivals." },
        { t: "Business travel", d: "Linate is Milan's business airport: we provide a service focused on punctuality and confidentiality, with a chauffeur at disposal for your day of meetings when needed." },
        { t: "Families, groups and luggage", d: "For families and small groups of up to 7 passengers, the Mercedes V-Class van offers plenty of room for luggage. Tell us passengers and bags in the form and we will confirm the ideal vehicle." },
      ],
      faqs: [
        { q: "Where do I find my chauffeur at Linate?", a: "In the terminal arrivals area, right after baggage claim, holding a board with your name. Before the journey you receive all the meeting point details." },
        { q: "What happens if my flight is delayed?", a: "We track your flight in real time and adjust the welcome time: your chauffeur waits for you at arrivals." },
        { q: "How long is the transfer from Linate to the centre?", a: "Linate is about 7 km from central Milan: the ride usually takes 15–25 minutes, depending on traffic and your exact destination." },
        { q: "Can I book for several passengers or with lots of luggage?", a: "Yes. The sedan is ideal for 1–3 passengers; the V-Class van seats up to 7 with bulky luggage. Tell us your needs in the request form." },
        { q: "How far in advance should I book?", a: "The service works by reservation: send your request as soon as you know your flight details. For last-minute needs, message us on WhatsApp and we will do our best." },
      ],
      ctaTitle: "Book your Linate transfer",
      ctaText: "Request a free quote: we reply quickly with a tailored proposal for your journey.",
    },
  },
  "transfer-orio-al-serio": {
    image: IMAGES.airports,
    it: {
      metaTitle: "Transfer Orio al Serio | NCC Bergamo Milano — FIRST MILANO",
      metaDesc: "Transfer privato NCC da e per l'aeroporto di Bergamo Orio al Serio (BGY) con autista professionale e Mercedes. Prezzo concordato, monitoraggio volo. FIRST MILANO.",
      eyebrow: "Transfer Aeroportuale",
      h1: "NCC Orio al Serio (Bergamo) – Transfer Privato con Autista",
      intro: "L'aeroporto di Bergamo Orio al Serio (BGY), scalo di molti voli nazionali e low-cost, dista circa 50 km da Milano. Con FIRST MILANO il viaggio diventa parte della vacanza: autista professionale, vettura Mercedes e prezzo concordato in anticipo.",
      highlights: [
        "Circa 50 km da Milano — 50/60 minuti di viaggio",
        "Perfetto per voli low-cost con orari insoliti, anche notturni su prenotazione",
        "Monitoraggio del volo e accoglienza agli arrivi con cartello",
        "Prezzo chiaro concordato prima della partenza",
        "Ideale per gruppi e famiglie con molti bagagli (Mercedes Classe V)",
        "Disponibile anche per stazioni sciistiche e località turistiche",
      ],
      steps: [
        { t: "Prenota", d: "Indica volo, data e orario: ti confermiamo disponibilità e prezzo." },
        { t: "Viaggia", d: "Autista puntuale, viaggio confortevole anche negli orari più scomodi." },
        { t: "Arriva", d: "Arrivo al terminal senza pensieri o accoglienza diretta al tuo rientro." },
      ],
      sections: [
        { t: "Accoglienza in aeroporto", d: "Al tuo atterraggio a Orio al Serio l'autista ti aspetta nell'area arrivi con un cartello con il tuo nome. Dopo l'incontro in area arrivi, raggiungi direttamente la vettura per il trasferimento verso Milano o la tua destinazione." },
        { t: "Monitoraggio del volo e ritardi", d: "Indicaci il numero del volo: seguiamo l'atterraggio in tempo reale e adattiamo l'orario di accoglienza. Anche con ritardi serali o notturni, l'autista ti aspetta." },
        { t: "Dove incontri l'autista", d: "Il punto d'incontro è nell'area arrivi del terminal, subito dopo l'uscita dal ritiro bagagli. Prima del viaggio ricevi tutti i dettagli e il recapito dell'autista." },
        { t: "Transfer aeroporto → Milano e Milano → aeroporto", d: "Servizio in entrambe le direzioni, a qualsiasi ora su prenotazione: ideale per i voli low-cost del mattino presto o della tarda sera, quando i collegamenti pubblici sono ridotti." },
        { t: "Famiglie e gruppi", d: "Orio al Serio è lo scalo di molte vacanze: con il van Mercedes Classe V viaggiano comodi fino a 7 passeggeri con valigie, passeggini e attrezzature." },
        { t: "Bagagli e attrezzature", d: "Sci, snowboard, borse da golf: segnala le attrezzature nelle note della richiesta e ti confermeremo la vettura con lo spazio giusto." },
      ],
      faqs: [
        { q: "Dove trovo l'autista a Orio al Serio?", a: "Nell'area arrivi del terminal, subito dopo il ritiro bagagli, con un cartello con il tuo nome. Prima del viaggio ricevi tutti i dettagli del punto d'incontro." },
        { q: "Il mio volo atterra tardi la sera: il servizio è disponibile?", a: "Sì, il servizio è disponibile a qualsiasi ora su prenotazione, anche per arrivi e partenze notturni. Monitoriamo il volo e l'autista ti aspetta anche in caso di ritardo." },
        { q: "Quanto dura il transfer da Orio al Serio a Milano?", a: "Circa 50–60 minuti per il centro di Milano, in base al traffico e alla destinazione esatta." },
        { q: "Posso prenotare per più passeggeri o con molti bagagli?", a: "Sì. La berlina è ideale per 1–3 passeggeri; il van Classe V accoglie fino a 7 passeggeri con bagagli voluminosi. Indica le tue esigenze nel modulo di richiesta." },
        { q: "Quanto prima è consigliabile prenotare?", a: "Il servizio è su prenotazione: invia la richiesta appena conosci i dettagli del volo. Per l'ultimo minuto, scrivici su WhatsApp e faremo il possibile per aiutarti." },
      ],
      ctaTitle: "Prenota il tuo transfer per Orio al Serio",
      ctaText: "Richiedi un preventivo gratuito: ti rispondiamo rapidamente con la proposta per il tuo viaggio.",
    },
    en: {
      metaTitle: "Orio al Serio Transfer | Bergamo Milan Chauffeur — FIRST MILANO",
      metaDesc: "Private chauffeur transfer to and from Bergamo Orio al Serio Airport (BGY) with Mercedes vehicles. Price agreed in advance, flight tracking. FIRST MILANO.",
      eyebrow: "Airport Transfer",
      h1: "Orio al Serio (Bergamo) Airport Transfer – Private Chauffeur",
      intro: "Bergamo Orio al Serio Airport (BGY), hub for many national and low-cost flights, is about 50 km from Milan. With FIRST MILANO the journey becomes part of the trip: professional chauffeur, Mercedes vehicle and a price agreed in advance.",
      highlights: [
        "About 50 km from Milan — 50/60 minutes journey time",
        "Perfect for low-cost flights at unusual hours, also at night by reservation",
        "Flight tracking and arrivals welcome with name board",
        "Clear price agreed before departure",
        "Ideal for groups and families with lots of luggage (Mercedes V-Class)",
        "Also available for ski resorts and tourist destinations",
      ],
      steps: [
        { t: "Book", d: "Tell us your flight, date and time: we confirm availability and price." },
        { t: "Travel", d: "A punctual chauffeur and a comfortable ride, even at the most inconvenient hours." },
        { t: "Arrive", d: "A carefree arrival at the terminal, or a personal welcome on your return." },
      ],
      sections: [
        { t: "Meet & greet at the airport", d: "When you land at Orio al Serio your chauffeur is waiting in the arrivals hall with a board bearing your name. After meeting in arrivals, you go directly to the vehicle for your transfer to Milan or your destination." },
        { t: "Flight tracking and delays", d: "Give us your flight number: we follow the landing in real time and adjust the welcome time. Even with late-night delays, your chauffeur waits for you." },
        { t: "Where you meet your chauffeur", d: "The meeting point is in the terminal arrivals area, just after the baggage claim exit. Before the journey you receive all the details and your chauffeur's contact." },
        { t: "Airport → Milan and Milan → airport", d: "Service in both directions, at any hour by reservation: ideal for early-morning or late-night low-cost flights, when public transport is limited." },
        { t: "Families and groups", d: "Orio al Serio is the airport of many holidays: with the Mercedes V-Class van up to 7 passengers travel comfortably with suitcases, strollers and equipment." },
        { t: "Luggage and equipment", d: "Skis, snowboards, golf bags: mention any equipment in the notes of your request and we will confirm the vehicle with the right space." },
      ],
      faqs: [
        { q: "Where do I find my chauffeur at Orio al Serio?", a: "In the terminal arrivals area, right after baggage claim, holding a board with your name. Before the journey you receive all the meeting point details." },
        { q: "My flight lands late at night: is the service available?", a: "Yes, the service is available at any hour by reservation, including night arrivals and departures. We track the flight and your chauffeur waits even in case of delay." },
        { q: "How long is the transfer from Orio al Serio to Milan?", a: "About 50–60 minutes to central Milan, depending on traffic and your exact destination." },
        { q: "Can I book for several passengers or with lots of luggage?", a: "Yes. The sedan is ideal for 1–3 passengers; the V-Class van seats up to 7 with bulky luggage. Tell us your needs in the request form." },
        { q: "How far in advance should I book?", a: "The service works by reservation: send your request as soon as you know your flight details. For last-minute needs, message us on WhatsApp and we will do our best." },
      ],
      ctaTitle: "Book your Orio al Serio transfer",
      ctaText: "Request a free quote: we reply quickly with a tailored proposal for your journey.",
    },
  },
  "autista-a-disposizione": {
    image: IMAGES.fleetSedan,
    it: {
      metaTitle: "Autista a Disposizione Milano | NCC a Ore — FIRST MILANO",
      metaDesc: "Autista privato a disposizione a Milano per ore o giornate intere: shopping, meeting, eventi e serate. Vettura Mercedes con conducente sempre pronto. FIRST MILANO.",
      eyebrow: "Servizio a Ore",
      h1: "Autista a Disposizione a Milano",
      intro: "Una vettura Mercedes con autista professionale sempre al tuo fianco: per una giornata di shopping in Quadrilatero, una serie di meeting in città, una serata a teatro o un evento importante. Con FIRST MILANO l'autista ti aspetta dove e quando vuoi.",
      highlights: [
        "Disponibile per alcune ore, l'intera giornata o più giorni",
        "Itinerario completamente flessibile, modificabile in tempo reale",
        "L'autista ti attende a ogni tappa: zero attese, zero parcheggi da cercare",
        "Massima discrezione e riservatezza durante tutto il servizio",
        "Ideale per shopping, meeting, visite mediche, cerimonie e serate",
        "Berlina Mercedes o van Classe V in base alle esigenze",
      ],
      steps: [
        { t: "Raccontaci la giornata", d: "Indicaci durata e tappe indicative: prepariamo un preventivo su misura." },
        { t: "L'autista è tuo", d: "Vettura e conducente a tua completa disposizione per tutto il periodo." },
        { t: "Cambia programma liberamente", d: "Imprevisti o nuove tappe? L'autista si adatta in tempo reale." },
      ],
      ctaTitle: "Richiedi il tuo autista a disposizione",
      ctaText: "Raccontaci la tua giornata: ti rispondiamo con una proposta personalizzata.",
    },
    en: {
      metaTitle: "Hourly Chauffeur Milan | Private Driver Hire — FIRST MILANO",
      metaDesc: "Private chauffeur at your disposal in Milan by the hour or for full days: shopping, meetings, events and evenings out. Mercedes vehicle with driver always ready. FIRST MILANO.",
      eyebrow: "Hourly Service",
      h1: "Chauffeur at Disposal in Milan",
      intro: "A Mercedes vehicle with a professional chauffeur always by your side: for a day of shopping in the Quadrilatero, a series of meetings across the city, a night at the theatre or an important event. With FIRST MILANO your chauffeur waits wherever and whenever you want.",
      highlights: [
        "Available for a few hours, a full day or several days",
        "Fully flexible itinerary, adjustable in real time",
        "Your chauffeur waits at every stop: without having to look for parking between stops",
        "Complete discretion and confidentiality throughout the service",
        "Ideal for shopping, meetings, medical visits, ceremonies and evenings",
        "Mercedes sedan or V-Class van according to your needs",
      ],
      steps: [
        { t: "Tell us about your day", d: "Share the duration and indicative stops: we prepare a tailored quote." },
        { t: "The chauffeur is yours", d: "Vehicle and driver entirely at your disposal for the whole period." },
        { t: "Change plans freely", d: "New stops or last-minute changes? Your chauffeur adapts in real time." },
      ],
      ctaTitle: "Request your chauffeur at disposal",
      ctaText: "Tell us about your day: we will reply with a personalised proposal.",
    },
  },
  "eventi-fashion-week": {
    image: IMAGES.fleetVan,
    it: {
      metaTitle: "NCC Eventi e Fashion Week Milano — FIRST MILANO",
      metaDesc: "Servizio NCC per eventi, fiere e Milano Fashion Week: transfer per ospiti, delegazioni e VIP con Mercedes e autisti professionisti. Discrezione e puntualità. FIRST MILANO.",
      eyebrow: "Eventi & Fashion",
      h1: "NCC per Eventi e Milano Fashion Week",
      intro: "Durante la Milano Fashion Week, le fiere e i grandi eventi, muoversi in città diventa una sfida. FIRST MILANO coordina transfer e autisti a disposizione per ospiti, delegazioni e clienti VIP, con la puntualità e la discrezione che queste occasioni richiedono.",
      highlights: [
        "Transfer per ospiti e delegazioni durante Fashion Week, Salone del Mobile e fiere",
        "Coordinamento di più vetture per eventi e cerimonie",
        "Autista a disposizione per tutta la durata dell'evento",
        "Massima riservatezza per ospiti pubblici e clienti VIP",
        "Vetture Mercedes berlina e van per singoli o gruppi",
        "Su richiesta, servizio di protezione personale qualificato",
      ],
      steps: [
        { t: "Pianifichiamo insieme", d: "Date, orari, tappe e numero di ospiti: costruiamo il piano dei trasporti." },
        { t: "Coordinamento", d: "Vetture e autisti assegnati, con referente dedicato per l'evento." },
        { t: "L'evento scorre", d: "Ospiti sempre puntuali e assistiti, dall'arrivo alla fine della serata." },
      ],
      ctaTitle: "Organizza i transfer per il tuo evento",
      ctaText: "Raccontaci l'evento: ti rispondiamo con una proposta completa e personalizzata.",
    },
    en: {
      metaTitle: "Chauffeur for Events & Milan Fashion Week — FIRST MILANO",
      metaDesc: "Chauffeur service for events, trade fairs and Milan Fashion Week: transfers for guests, delegations and VIPs with Mercedes and professional chauffeurs. FIRST MILANO.",
      eyebrow: "Events & Fashion",
      h1: "Chauffeur Service for Events & Milan Fashion Week",
      intro: "During Milan Fashion Week, trade fairs and major events, moving around the city becomes a challenge. FIRST MILANO coordinates transfers and chauffeurs at disposal for guests, delegations and VIP clients, with the punctuality and discretion these occasions demand.",
      highlights: [
        "Transfers for guests and delegations during Fashion Week, Salone del Mobile and trade fairs",
        "Coordination of multiple vehicles for events and ceremonies",
        "Chauffeur at disposal for the entire duration of the event",
        "Complete confidentiality for public figures and VIP clients",
        "Mercedes sedans and vans for individuals or groups",
        "On request, qualified personal protection service",
      ],
      steps: [
        { t: "We plan together", d: "Dates, times, stops and number of guests: we build the transport plan." },
        { t: "Coordination", d: "Vehicles and chauffeurs assigned, with a dedicated contact for your event." },
        { t: "The event flows", d: "Guests always on time and looked after, from arrival to the end of the evening." },
      ],
      ctaTitle: "Organise transfers for your event",
      ctaText: "Tell us about your event: we will reply with a complete, tailored proposal.",
    },
  },
  "milano-lago-di-como": {
    image: IMAGES.routeSedan,
    it: {
      metaTitle: "NCC Milano Lago di Como | Transfer Privato — FIRST MILANO",
      metaDesc: "Transfer privato con autista da Milano al Lago di Como (Como, Bellagio, Cernobbio, Tremezzo). Circa 1 ora di viaggio in Mercedes, prezzo concordato in anticipo. FIRST MILANO.",
      eyebrow: "Lunga Percorrenza",
      h1: "Transfer Privato Milano – Lago di Como",
      intro: "Il Lago di Como è una delle destinazioni più richieste da chi arriva a Milano: ville storiche, hotel di lusso e borghi sul lago. Con FIRST MILANO raggiungi Como, Cernobbio, Bellagio o Tremezzo con un transfer privato in Mercedes, senza cambi di treno né attese.",
      highlights: [
        "Circa 50 km da Milano — circa 1 ora di viaggio verso Como città",
        "Servizio porta a porta: hotel, ville e location direttamente sul lago",
        "Berlina Mercedes per 1–3 passeggeri o van Classe V fino a 7",
        "Prezzo concordato prima del servizio, con condizioni definite in anticipo",
        "Ideale anche per matrimoni ed eventi sul lago",
      ],
      steps: [
        { t: "Richiedi", d: "Indica data, orario e destinazione sul lago: ricevi rapidamente disponibilità e preventivo." },
        { t: "Parti", d: "L'autista ti prende all'indirizzo concordato — hotel, abitazione o aeroporto — e si occupa dei bagagli." },
        { t: "Arrivi", d: "Discesa direttamente all'ingresso della tua destinazione sul lago." },
      ],
      sections: [
        { t: "La tratta", d: "Da Milano il percorso più rapido segue l'autostrada A9 in direzione Como: circa 50 km e un'ora di viaggio verso Como città. Per Bellagio, Tremezzo e la sponda occidentale i tempi aumentano in base alla destinazione esatta: li concordiamo insieme al momento del preventivo." },
        { t: "Perché un transfer privato", d: "I collegamenti pubblici verso i borghi del lago richiedono spesso cambi e coincidenze. Con l'autista privato viaggi diretto, con i tuoi orari e i bagagli sempre con te: la soluzione più comoda soprattutto per chi arriva dagli aeroporti di Malpensa o Linate." },
        { t: "Soste e itinerari su misura", d: "Vuoi una sosta panoramica o una tappa intermedia? Il servizio è personalizzabile: segnala le tue preferenze nella richiesta e costruiamo l'itinerario insieme." },
      ],
      faqs: [
        { q: "Quanto dura il transfer da Milano al Lago di Como?", a: "Circa 1 ora per Como città (50 km). Per Bellagio, Tremezzo o altre località del lago i tempi variano: ti confermiamo la stima nel preventivo." },
        { q: "Potete prenderci direttamente in aeroporto?", a: "Sì: organizziamo transfer da Malpensa, Linate e Orio al Serio verso il Lago di Como, con monitoraggio del volo e accoglienza agli arrivi." },
        { q: "È possibile fare una sosta durante il viaggio?", a: "Sì, il servizio è personalizzabile: segnala la sosta desiderata nelle note della richiesta e la includiamo nel preventivo." },
        { q: "Quanto prima è consigliabile prenotare?", a: "Il servizio è su prenotazione: invia la richiesta appena conosci data e orario. Nei periodi di alta stagione sul lago consigliamo di prenotare con anticipo." },
      ],
      ctaTitle: "Prenota il tuo transfer per il Lago di Como",
      ctaText: "Richiedi disponibilità e prezzo: ti rispondiamo rapidamente con una proposta personalizzata.",
    },
    en: {
      metaTitle: "Milan to Lake Como Private Transfer | Chauffeur — FIRST MILANO",
      metaDesc: "Private chauffeur transfer from Milan to Lake Como (Como, Bellagio, Cernobbio, Tremezzo). About 1 hour in a Mercedes, price agreed in advance. FIRST MILANO.",
      eyebrow: "Long Distance",
      h1: "Private Transfer from Milan to Lake Como",
      intro: "Lake Como is one of the most requested destinations for travellers arriving in Milan: historic villas, luxury hotels and lakeside villages. With FIRST MILANO you reach Como, Cernobbio, Bellagio or Tremezzo with a private Mercedes transfer — without train changes and with a direct private transfer.",
      highlights: [
        "About 50 km from Milan — around 1 hour to Como town",
        "Door-to-door service: hotels, villas and venues right on the lake",
        "Mercedes sedan for 1–3 passengers or V-Class van up to 7",
        "Price agreed before the service, with terms defined in advance",
        "Ideal also for weddings and events on the lake",
      ],
      steps: [
        { t: "Request", d: "Tell us your date, time and destination on the lake: we reply quickly with availability and a quote." },
        { t: "Depart", d: "Your chauffeur picks you up at the agreed address — hotel, home or airport — and takes care of the luggage." },
        { t: "Arrive", d: "Drop-off right at the entrance of your destination on the lake." },
      ],
      sections: [
        { t: "The route", d: "From Milan the fastest route follows the A9 motorway towards Como: about 50 km and one hour to Como town. For Bellagio, Tremezzo and the western shore, timings depend on the exact destination — we confirm them with your quote." },
        { t: "Why a private transfer", d: "Public transport to the lake villages often involves changes and connections. With a private chauffeur you travel direct, on your schedule, with your luggage always with you: the most comfortable option especially when arriving at Malpensa or Linate." },
        { t: "Stops and tailored itineraries", d: "Would you like a scenic stop or an intermediate visit? The service can be tailored: tell us your preferences in the request and we build the itinerary together." },
      ],
      faqs: [
        { q: "How long is the transfer from Milan to Lake Como?", a: "About 1 hour to Como town (50 km). For Bellagio, Tremezzo or other lake destinations timings vary: we confirm the estimate with your quote." },
        { q: "Can you pick us up directly at the airport?", a: "Yes: we arrange transfers from Malpensa, Linate and Orio al Serio to Lake Como, with flight tracking and an arrivals welcome." },
        { q: "Is it possible to make a stop along the way?", a: "Yes, the service can be tailored: mention the desired stop in the notes of your request and we will include it in the quote." },
        { q: "How far in advance should I book?", a: "The service works by reservation: send your request as soon as you know your date and time. During high season on the lake we recommend booking early." },
      ],
      ctaTitle: "Book your transfer to Lake Como",
      ctaText: "Request availability and price: we reply quickly with a tailored proposal.",
    },
  },
  "milano-st-moritz": {
    image: IMAGES.routeVan,
    it: {
      metaTitle: "NCC Milano St. Moritz | Transfer Privato Engadina — FIRST MILANO",
      metaDesc: "Transfer privato con autista da Milano a St. Moritz e Engadina. Circa 3 ore in Mercedes, anche con attrezzatura da sci. Prezzo concordato in anticipo. FIRST MILANO.",
      eyebrow: "Lunga Percorrenza",
      h1: "Transfer Privato Milano – St. Moritz",
      intro: "St. Moritz e l'Engadina sono la meta alpina per eccellenza: sci, grand hotel ed eventi internazionali. Con FIRST MILANO raggiungi la Svizzera in totale comfort: circa 3 ore di viaggio in Mercedes, con spazio per bagagli e attrezzatura da sci.",
      highlights: [
        "Circa 180 km da Milano — circa 3 ore di viaggio",
        "Van Mercedes Classe V ideale per sci e bagagli voluminosi",
        "Servizio porta a porta verso hotel e chalet in Engadina",
        "Prezzo concordato in anticipo, pedaggi inclusi nel preventivo",
        "Disponibile anche per rientri e transfer da/per gli aeroporti",
      ],
      steps: [
        { t: "Richiedi", d: "Indica data, orario e destinazione in Engadina: ricevi disponibilità e preventivo." },
        { t: "Parti", d: "L'autista ti prende all'indirizzo concordato e sistema bagagli e attrezzature." },
        { t: "Arrivi", d: "Viaggio rilassato tra le Alpi e discesa direttamente al tuo hotel o chalet." },
      ],
      sections: [
        { t: "La tratta", d: "Da Milano si sale verso la Valtellina e si valica il Passo del Maloja: circa 180 km e 3 ore di viaggio in condizioni normali. In inverno i tempi possono variare per meteo e traffico: pianifichiamo la partenza con il giusto margine." },
        { t: "Perché un transfer privato", d: "Raggiungere St. Moritz con i mezzi pubblici richiede treno e coincidenze con bagagli e sci al seguito. Con l'autista privato viaggi diretto, in una vettura con spazio per tutta l'attrezzatura, e arrivi riposato." },
        { t: "Sci e attrezzature", d: "La Mercedes Classe V accoglie comodamente fino a 7 passeggeri con sci, snowboard e valigie. Segnala le attrezzature nella richiesta: ti confermiamo la vettura più adatta." },
      ],
      faqs: [
        { q: "Quanto dura il transfer da Milano a St. Moritz?", a: "Circa 3 ore (180 km) in condizioni normali. In inverno prevediamo margini più ampi in caso di neve: concordiamo l'orario di partenza ideale insieme." },
        { q: "C'è spazio per sci e snowboard?", a: "Sì: il van Mercedes Classe V è pensato proprio per bagagli voluminosi e attrezzature sportive. Indica sci e valigie nella richiesta." },
        { q: "Il servizio è disponibile anche per il rientro?", a: "Sì: organizziamo transfer di andata e ritorno, anche in giornate diverse, e collegamenti da/per gli aeroporti di Milano." },
        { q: "Il prezzo include pedaggi e trafori?", a: "Il preventivo è concordato in anticipo e chiaro: ti confermiamo tutte le voci incluse prima della conferma, con tutte le voci incluse confermate prima della prenotazione." },
      ],
      ctaTitle: "Prenota il tuo transfer per St. Moritz",
      ctaText: "Richiedi disponibilità e prezzo: ti rispondiamo rapidamente con una proposta personalizzata.",
    },
    en: {
      metaTitle: "Milan to St. Moritz Private Transfer | Chauffeur — FIRST MILANO",
      metaDesc: "Private chauffeur transfer from Milan to St. Moritz and the Engadin. About 3 hours in a Mercedes, with room for ski equipment. Price agreed in advance. FIRST MILANO.",
      eyebrow: "Long Distance",
      h1: "Private Transfer from Milan to St. Moritz",
      intro: "St. Moritz and the Engadin are the quintessential Alpine destination: skiing, grand hotels and international events. With FIRST MILANO you reach Switzerland in total comfort: about 3 hours in a Mercedes, with room for luggage and ski equipment.",
      highlights: [
        "About 180 km from Milan — around 3 hours journey time",
        "Mercedes V-Class van ideal for skis and bulky luggage",
        "Door-to-door service to hotels and chalets across the Engadin",
        "Price agreed in advance, tolls included in the quote",
        "Also available for return trips and airport connections",
      ],
      steps: [
        { t: "Request", d: "Tell us your date, time and destination in the Engadin: we reply with availability and a quote." },
        { t: "Depart", d: "Your chauffeur picks you up at the agreed address and stows luggage and equipment." },
        { t: "Arrive", d: "A relaxed ride through the Alps, with drop-off right at your hotel or chalet." },
      ],
      sections: [
        { t: "The route", d: "From Milan the route climbs through the Valtellina valley and crosses the Maloja Pass: about 180 km and 3 hours in normal conditions. In winter, timings can vary with weather and traffic: we plan departure with the right margin." },
        { t: "Why a private transfer", d: "Reaching St. Moritz by public transport means trains and connections with luggage and skis in tow. With a private chauffeur you travel direct, in a vehicle with room for all your equipment, and arrive rested." },
        { t: "Skis and equipment", d: "The Mercedes V-Class comfortably seats up to 7 passengers with skis, snowboards and suitcases. Mention your equipment in the request and we will confirm the most suitable vehicle." },
      ],
      faqs: [
        { q: "How long is the transfer from Milan to St. Moritz?", a: "About 3 hours (180 km) in normal conditions. In winter we allow wider margins in case of snow: we agree the ideal departure time together." },
        { q: "Is there room for skis and snowboards?", a: "Yes: the Mercedes V-Class van is designed exactly for bulky luggage and sports equipment. List skis and suitcases in your request." },
        { q: "Is the service available for the return trip too?", a: "Yes: we arrange one-way or round-trip transfers, also on different days, and connections to and from Milan's airports." },
        { q: "Does the price include tolls?", a: "The quote is agreed in advance and transparent: we confirm everything that is included before you confirm, with all included items confirmed before booking." },
      ],
      ctaTitle: "Book your transfer to St. Moritz",
      ctaText: "Request availability and price: we reply quickly with a tailored proposal.",
    },
  },
  "milano-portofino": {
    image: IMAGES.fleetSedan,
    it: {
      metaTitle: "NCC Milano Portofino | Transfer Privato Riviera — FIRST MILANO",
      metaDesc: "Transfer privato con autista da Milano a Portofino, Santa Margherita e Rapallo. Circa 2 ore e 15 in Mercedes, servizio porta a porta. Prezzo concordato. FIRST MILANO.",
      eyebrow: "Lunga Percorrenza",
      h1: "Transfer Privato Milano – Portofino",
      intro: "Portofino e la Riviera di Levante sono tra le mete più eleganti del Mediterraneo. Con FIRST MILANO lasci Milano e arrivi direttamente nel borgo o al tuo hotel sul mare: circa 2 ore e un quarto di viaggio in Mercedes, senza pensieri di treni o parcheggi.",
      highlights: [
        "Circa 175 km da Milano — circa 2 ore e 15 di viaggio",
        "Servizio porta a porta verso Portofino, Santa Margherita, Rapallo e Paraggi",
        "Berlina Mercedes o van Classe V in base a passeggeri e bagagli",
        "Prezzo concordato in anticipo",
        "Ideale per weekend, eventi e cerimonie sul mare",
      ],
      steps: [
        { t: "Richiedi", d: "Indica data, orario e destinazione sulla Riviera: ricevi disponibilità e preventivo." },
        { t: "Parti", d: "L'autista ti prende all'indirizzo concordato e si occupa dei bagagli." },
        { t: "Arrivi", d: "Discesa il più vicino possibile alla tua destinazione, anche nelle zone a traffico limitato consentite." },
      ],
      sections: [
        { t: "La tratta", d: "Da Milano si percorre l'autostrada A7 verso Genova e poi la A12 in direzione Rapallo: circa 175 km e 2 ore e 15 minuti in condizioni normali. L'ultimo tratto verso Portofino è panoramico ma stretto: ci pensa l'autista." },
        { t: "Perché un transfer privato", d: "A Portofino i parcheggi sono pochissimi e in estate il traffico è intenso. Con l'autista privato arrivi diretto, senza cercare parcheggio né trascinare valigie, e al rientro ti riprendiamo all'orario concordato." },
        { t: "Eventi e cerimonie", d: "Matrimoni ed eventi sul mare richiedono puntualità perfetta: organizziamo transfer per sposi, ospiti e delegazioni, anche con più vetture coordinate." },
      ],
      faqs: [
        { q: "Quanto dura il transfer da Milano a Portofino?", a: "Circa 2 ore e 15 minuti (175 km) in condizioni normali di traffico. Nei weekend estivi consigliamo partenze con margine." },
        { q: "L'autista può entrare nel centro di Portofino?", a: "Portofino ha zone a traffico limitato: ti accompagniamo al punto più vicino consentito alla tua destinazione, concordato in anticipo." },
        { q: "Organizzate transfer per matrimoni o gruppi?", a: "Sì: per eventi e cerimonie coordiniamo anche più vetture Mercedes, berline e van fino a 7 passeggeri ciascuno." },
        { q: "Quanto prima è consigliabile prenotare?", a: "Il servizio è su prenotazione: in estate e nei weekend consigliamo di inviare la richiesta con anticipo per aumentare la possibilità di trovare disponibilità." },
      ],
      ctaTitle: "Prenota il tuo transfer per Portofino",
      ctaText: "Richiedi disponibilità e prezzo: ti rispondiamo rapidamente con una proposta personalizzata.",
    },
    en: {
      metaTitle: "Milan to Portofino Private Transfer | Chauffeur — FIRST MILANO",
      metaDesc: "Private chauffeur transfer from Milan to Portofino, Santa Margherita and Rapallo. About 2h15 in a Mercedes, door-to-door service. Price agreed in advance. FIRST MILANO.",
      eyebrow: "Long Distance",
      h1: "Private Transfer from Milan to Portofino",
      intro: "Portofino and the Riviera di Levante are among the most elegant destinations on the Mediterranean. With FIRST MILANO you leave Milan and arrive directly in the village or at your seaside hotel: about 2 hours and 15 minutes in a Mercedes, with no trains or parking to worry about.",
      highlights: [
        "About 175 km from Milan — around 2h15 journey time",
        "Door-to-door service to Portofino, Santa Margherita, Rapallo and Paraggi",
        "Mercedes sedan or V-Class van according to passengers and luggage",
        "Price agreed in advance",
        "Ideal for weekends, events and ceremonies by the sea",
      ],
      steps: [
        { t: "Request", d: "Tell us your date, time and destination on the Riviera: we reply with availability and a quote." },
        { t: "Depart", d: "Your chauffeur picks you up at the agreed address and takes care of the luggage." },
        { t: "Arrive", d: "Drop-off as close as possible to your destination, within the permitted traffic zones." },
      ],
      sections: [
        { t: "The route", d: "From Milan we take the A7 motorway towards Genoa and then the A12 towards Rapallo: about 175 km and 2h15 in normal conditions. The last stretch to Portofino is scenic but narrow: your chauffeur takes care of it." },
        { t: "Why a private transfer", d: "In Portofino parking is extremely limited and summer traffic is heavy. With a private chauffeur you arrive directly, without searching for parking or dragging suitcases, and on your return we pick you up at the agreed time." },
        { t: "Events and ceremonies", d: "Weddings and events by the sea demand perfect punctuality: we arrange transfers for couples, guests and delegations, also with several coordinated vehicles." },
      ],
      faqs: [
        { q: "How long is the transfer from Milan to Portofino?", a: "About 2 hours and 15 minutes (175 km) in normal traffic. On summer weekends we recommend allowing extra margin." },
        { q: "Can the chauffeur drive into Portofino centre?", a: "Portofino has limited traffic zones: we take you to the closest permitted point to your destination, agreed in advance." },
        { q: "Do you arrange transfers for weddings or groups?", a: "Yes: for events and ceremonies we can coordinate several Mercedes vehicles, sedans and vans seating up to 7 passengers each." },
        { q: "How far in advance should I book?", a: "The service works by reservation: in summer and at weekends we recommend sending your request early to improve the chance of availability." },
      ],
      ctaTitle: "Book your transfer to Portofino",
      ctaText: "Request availability and price: we reply quickly with a tailored proposal.",
    },
  },
  "milano-venezia": {
    image: IMAGES.airports,
    it: {
      metaTitle: "NCC Milano Venezia | Transfer Privato con Autista — FIRST MILANO",
      metaDesc: "Transfer privato con autista da Milano a Venezia (Piazzale Roma e terminal crociere). Circa 3 ore in Mercedes, porta a porta. Prezzo concordato in anticipo. FIRST MILANO.",
      eyebrow: "Lunga Percorrenza",
      h1: "Transfer Privato Milano – Venezia",
      intro: "Venezia si raggiunge in auto fino a Piazzale Roma o al terminal crociere: da lì ci si muove a piedi o in battello. Con FIRST MILANO il viaggio da Milano è comodo e diretto: circa 3 ore in Mercedes, con arrivo al punto più vicino possibile alla tua sistemazione.",
      highlights: [
        "Circa 270 km da Milano — circa 3 ore di viaggio",
        "Arrivo a Piazzale Roma, stazione Santa Lucia o terminal crociere",
        "Ideale per imbarchi crociera con molti bagagli",
        "Berlina Mercedes o van Classe V fino a 7 passeggeri",
        "Prezzo concordato in anticipo",
      ],
      steps: [
        { t: "Richiedi", d: "Indica data, orario e punto di arrivo a Venezia: ricevi disponibilità e preventivo." },
        { t: "Parti", d: "L'autista ti prende all'indirizzo concordato e sistema i bagagli." },
        { t: "Arrivi", d: "Discesa a Piazzale Roma o al terminal crociere, pronto per proseguire in battello o a piedi." },
      ],
      sections: [
        { t: "La tratta", d: "Da Milano si percorre l'autostrada A4 in direzione Venezia: circa 270 km e 3 ore in condizioni normali. L'auto arriva fino al limite della zona pedonale: Piazzale Roma, la stazione Santa Lucia o il terminal crociere Marittima." },
        { t: "Perché un transfer privato", d: "Con valigie e imbarchi crociera, treno e coincidenze diventano faticosi. Con l'autista privato parti dal tuo indirizzo e scendi direttamente al terminal o al piazzale, con i bagagli sempre assistiti." },
        { t: "Crociere e imbarchi", d: "Per chi si imbarca da Venezia: indicaci l'orario di imbarco e pianifichiamo la partenza da Milano con il giusto margine. Il van Classe V è ideale per i bagagli da crociera." },
      ],
      faqs: [
        { q: "Dove esattamente lascia l'autista a Venezia?", a: "Le auto arrivano fino a Piazzale Roma, alla stazione Santa Lucia o al terminal crociere: ti accompagniamo al punto più comodo per la tua sistemazione o il tuo imbarco." },
        { q: "Quanto dura il transfer da Milano a Venezia?", a: "Circa 3 ore (270 km) in condizioni normali di traffico." },
        { q: "Viaggiamo in tanti con valigie da crociera: che vettura serve?", a: "Il van Mercedes Classe V accoglie fino a 7 passeggeri con bagagli voluminosi. Indica passeggeri e valigie nella richiesta." },
        { q: "Organizzate anche il rientro da Venezia a Milano?", a: "Sì: prenotiamo andata e ritorno, anche in giornate diverse, con orari concordati." },
      ],
      ctaTitle: "Prenota il tuo transfer per Venezia",
      ctaText: "Richiedi disponibilità e prezzo: ti rispondiamo rapidamente con una proposta personalizzata.",
    },
    en: {
      metaTitle: "Milan to Venice Private Transfer | Chauffeur — FIRST MILANO",
      metaDesc: "Private chauffeur transfer from Milan to Venice (Piazzale Roma and cruise terminal). About 3 hours in a Mercedes, door-to-door. Price agreed in advance. FIRST MILANO.",
      eyebrow: "Long Distance",
      h1: "Private Transfer from Milan to Venice",
      intro: "Venice is reached by car as far as Piazzale Roma or the cruise terminal: from there you move on foot or by boat. With FIRST MILANO the journey from Milan is comfortable and direct: about 3 hours in a Mercedes, arriving at the closest possible point to your accommodation.",
      highlights: [
        "About 270 km from Milan — around 3 hours journey time",
        "Arrival at Piazzale Roma, Santa Lucia station or the cruise terminal",
        "Ideal for cruise embarkations with plenty of luggage",
        "Mercedes sedan or V-Class van up to 7 passengers",
        "Price agreed in advance",
      ],
      steps: [
        { t: "Request", d: "Tell us your date, time and arrival point in Venice: we reply with availability and a quote." },
        { t: "Depart", d: "Your chauffeur picks you up at the agreed address and stows the luggage." },
        { t: "Arrive", d: "Drop-off at Piazzale Roma or the cruise terminal, ready to continue by boat or on foot." },
      ],
      sections: [
        { t: "The route", d: "From Milan we follow the A4 motorway towards Venice: about 270 km and 3 hours in normal conditions. Cars reach the edge of the pedestrian zone: Piazzale Roma, Santa Lucia station or the Marittima cruise terminal." },
        { t: "Why a private transfer", d: "With suitcases and a cruise to catch, trains and connections become tiring. With a private chauffeur you leave from your address and step out right at the terminal or the square, with your luggage always looked after." },
        { t: "Cruises and embarkation", d: "If you are boarding in Venice: tell us your embarkation time and we will plan the departure from Milan with the right margin. The V-Class van is ideal for cruise luggage." },
      ],
      faqs: [
        { q: "Where exactly does the chauffeur drop us in Venice?", a: "Cars can reach Piazzale Roma, Santa Lucia station or the cruise terminal: we take you to the most convenient point for your accommodation or embarkation." },
        { q: "How long is the transfer from Milan to Venice?", a: "About 3 hours (270 km) in normal traffic." },
        { q: "We are a group with cruise suitcases: which vehicle do we need?", a: "The Mercedes V-Class van seats up to 7 passengers with bulky luggage. Tell us passengers and suitcases in your request." },
        { q: "Do you also arrange the return from Venice to Milan?", a: "Yes: we book one-way or round-trip transfers, also on different days, at agreed times." },
      ],
      ctaTitle: "Book your transfer to Venice",
      ctaText: "Request availability and price: we reply quickly with a tailored proposal.",
    },
  },
  "milano-firenze": {
    image: IMAGES.routeSedan,
    it: {
      metaTitle: "NCC Milano Firenze | Transfer Privato con Autista — FIRST MILANO",
      metaDesc: "Transfer privato con autista da Milano a Firenze: circa 3 ore e 15 in Mercedes, porta a porta. Ideale per business ed eventi come Pitti. Prezzo concordato. FIRST MILANO.",
      eyebrow: "Lunga Percorrenza",
      h1: "Transfer Privato Milano – Firenze",
      intro: "Firenze è una destinazione abituale per business, cultura ed eventi come Pitti Immagine. Con FIRST MILANO viaggi da Milano in pieno comfort: circa 3 ore e un quarto in Mercedes, lavorando o riposando mentre l'autista guida.",
      highlights: [
        "Circa 305 km da Milano — circa 3 ore e 15 di viaggio",
        "Ideale per business travel, Pitti Immagine e fiere",
        "Arrivo diretto a hotel, centro storico o Fortezza da Basso",
        "Possibilità di autista a disposizione durante il soggiorno",
        "Prezzo concordato in anticipo",
      ],
      steps: [
        { t: "Richiedi", d: "Indica data, orario e destinazione a Firenze: ricevi disponibilità e preventivo." },
        { t: "Parti", d: "L'autista ti prende all'indirizzo concordato: il viaggio è tempo tuo, per lavorare o rilassarti." },
        { t: "Arrivi", d: "Discesa direttamente alla tua destinazione, anche nelle vie del centro consentite." },
      ],
      sections: [
        { t: "La tratta", d: "Da Milano si percorre l'autostrada A1 in direzione Bologna e Firenze: circa 305 km e 3 ore e 15 minuti in condizioni normali. Un viaggio diretto, senza cambi né attese in stazione." },
        { t: "Perché un transfer privato", d: "Per chi viaggia per lavoro, il transfer privato trasforma tre ore di spostamento in tempo utile: puoi preparare meeting, fare telefonate in riservatezza o semplicemente riposare. E nessun vincolo di orari ferroviari." },
        { t: "Eventi e fiere", d: "In occasione di Pitti Immagine e delle grandi fiere fiorentine organizziamo transfer per ospiti e delegazioni, con autista a disposizione per l'intera durata dell'evento." },
      ],
      faqs: [
        { q: "Quanto dura il transfer da Milano a Firenze?", a: "Circa 3 ore e 15 minuti (305 km) in condizioni normali di traffico." },
        { q: "L'auto può entrare nel centro storico di Firenze?", a: "Firenze ha una ZTL: ti accompagniamo alla tua destinazione o al punto più vicino consentito, concordato in anticipo con l'autista." },
        { q: "Posso lavorare durante il viaggio?", a: "Sì: le nostre Mercedes offrono comfort e riservatezza, così il viaggio diventa tempo utile per lavorare o riposare." },
        { q: "Organizzate transfer per eventi come Pitti?", a: "Sì: per fiere ed eventi coordiniamo transfer e autisti a disposizione, anche con più vetture per delegazioni." },
      ],
      ctaTitle: "Prenota il tuo transfer per Firenze",
      ctaText: "Richiedi disponibilità e prezzo: ti rispondiamo rapidamente con una proposta personalizzata.",
    },
    en: {
      metaTitle: "Milan to Florence Private Transfer | Chauffeur — FIRST MILANO",
      metaDesc: "Private chauffeur transfer from Milan to Florence: about 3h15 in a Mercedes, door-to-door. Ideal for business and events such as Pitti. Price agreed in advance. FIRST MILANO.",
      eyebrow: "Long Distance",
      h1: "Private Transfer from Milan to Florence",
      intro: "Florence is a regular destination for business, culture and events such as Pitti Immagine. With FIRST MILANO you travel from Milan in complete comfort: about 3 hours and 15 minutes in a Mercedes, working or resting while your chauffeur drives.",
      highlights: [
        "About 305 km from Milan — around 3h15 journey time",
        "Ideal for business travel, Pitti Immagine and trade fairs",
        "Direct arrival at hotels, the historic centre or Fortezza da Basso",
        "Chauffeur at disposal available during your stay",
        "Price agreed in advance",
      ],
      steps: [
        { t: "Request", d: "Tell us your date, time and destination in Florence: we reply with availability and a quote." },
        { t: "Depart", d: "Your chauffeur picks you up at the agreed address: the journey is your time, to work or unwind." },
        { t: "Arrive", d: "Drop-off right at your destination, including permitted streets in the historic centre." },
      ],
      sections: [
        { t: "The route", d: "From Milan we take the A1 motorway towards Bologna and Florence: about 305 km and 3h15 in normal conditions. A direct ride, with no changes or station waiting." },
        { t: "Why a private transfer", d: "For business travellers, a private transfer turns three hours of travel into useful time: prepare meetings, take calls in privacy or simply rest. And no railway timetables to obey." },
        { t: "Events and fairs", d: "During Pitti Immagine and Florence's major fairs we arrange transfers for guests and delegations, with chauffeurs at disposal for the entire event." },
      ],
      faqs: [
        { q: "How long is the transfer from Milan to Florence?", a: "About 3 hours and 15 minutes (305 km) in normal traffic." },
        { q: "Can the car enter Florence's historic centre?", a: "Florence has a restricted traffic zone: we take you to your destination or the closest permitted point, agreed in advance with your chauffeur." },
        { q: "Can I work during the journey?", a: "Yes: our Mercedes vehicles offer comfort and privacy, so the journey becomes useful time to work or rest." },
        { q: "Do you arrange transfers for events such as Pitti?", a: "Yes: for fairs and events we coordinate transfers and chauffeurs at disposal, also with several vehicles for delegations." },
      ],
      ctaTitle: "Book your transfer to Florence",
      ctaText: "Request availability and price: we reply quickly with a tailored proposal.",
    },
  },
  "milano-roma": {
    image: IMAGES.fleetVan,
    it: {
      metaTitle: "NCC Milano Roma | Transfer Privato con Autista — FIRST MILANO",
      metaDesc: "Transfer privato con autista da Milano a Roma: circa 5 ore e 45 in Mercedes, porta a porta. Comfort, riservatezza e prezzo concordato in anticipo. FIRST MILANO.",
      eyebrow: "Lunga Percorrenza",
      h1: "Transfer Privato Milano – Roma",
      intro: "Quando serve spostarsi da Milano a Roma senza vincoli di orari, il transfer privato è la soluzione più flessibile: circa 5 ore e tre quarti di viaggio in Mercedes, con la possibilità di fermate intermedie e arrivo diretto alla tua destinazione.",
      highlights: [
        "Circa 575 km da Milano — circa 5 ore e 45 di viaggio",
        "Partenza a qualsiasi ora, su prenotazione",
        "Possibilità di fermate intermedie su richiesta",
        "Berlina Mercedes o van Classe V fino a 7 passeggeri",
        "Prezzo concordato in anticipo, tutto incluso nel preventivo",
      ],
      steps: [
        { t: "Richiedi", d: "Indica data, orario e destinazione a Roma: ricevi disponibilità e preventivo dettagliato." },
        { t: "Parti", d: "L'autista ti prende all'indirizzo concordato, anche all'alba o in tarda serata." },
        { t: "Arrivi", d: "Discesa direttamente alla tua destinazione a Roma, con eventuali soste concordate lungo il percorso." },
      ],
      sections: [
        { t: "La tratta", d: "Da Milano si percorre l'autostrada A1 attraverso Bologna e Firenze fino a Roma: circa 575 km e 5 ore e 45 minuti in condizioni normali. Su richiesta pianifichiamo fermate per pause o appuntamenti intermedi." },
        { t: "Perché un transfer privato", d: "Per delegazioni, famiglie con molti bagagli o chi ha orari fuori dai collegamenti standard, il transfer privato offre flessibilità totale: si parte quando vuoi tu e si arriva direttamente a destinazione, senza cambi." },
        { t: "Fermate intermedie", d: "Bologna, Firenze o una pausa pranzo lungo il percorso: il servizio è personalizzabile. Segnala le tappe desiderate nella richiesta e le includiamo nel preventivo." },
      ],
      faqs: [
        { q: "Quanto dura il transfer da Milano a Roma?", a: "Circa 5 ore e 45 minuti (575 km) in condizioni normali, escluse eventuali soste concordate." },
        { q: "È possibile fare fermate intermedie?", a: "Sì: su richiesta inseriamo fermate per pause o appuntamenti lungo il percorso, incluse nel preventivo concordato in anticipo." },
        { q: "Si può partire di notte o all'alba?", a: "Sì, il servizio è su prenotazione a qualsiasi ora: indica l'orario preferito nel modulo di richiesta." },
        { q: "Quanti passeggeri e bagagli potete trasportare?", a: "La berlina è ideale per 1–3 passeggeri; il van Mercedes Classe V accoglie fino a 7 passeggeri con bagagli. Indica le tue esigenze nella richiesta." },
      ],
      ctaTitle: "Prenota il tuo transfer per Roma",
      ctaText: "Richiedi disponibilità e prezzo: ti rispondiamo rapidamente con una proposta personalizzata.",
    },
    en: {
      metaTitle: "Milan to Rome Private Transfer | Chauffeur — FIRST MILANO",
      metaDesc: "Private chauffeur transfer from Milan to Rome: about 5h45 in a Mercedes, door-to-door. Comfort, privacy and a price agreed in advance. FIRST MILANO.",
      eyebrow: "Long Distance",
      h1: "Private Transfer from Milan to Rome",
      intro: "When you need to travel from Milan to Rome without timetable constraints, a private transfer is the most flexible solution: about 5 hours and 45 minutes in a Mercedes, with the option of intermediate stops and direct arrival at your destination.",
      highlights: [
        "About 575 km from Milan — around 5h45 journey time",
        "Departure at any hour, by reservation",
        "Intermediate stops available on request",
        "Mercedes sedan or V-Class van up to 7 passengers",
        "Price agreed in advance, everything included in the quote",
      ],
      steps: [
        { t: "Request", d: "Tell us your date, time and destination in Rome: we reply with availability and a detailed quote." },
        { t: "Depart", d: "Your chauffeur picks you up at the agreed address, even at dawn or late in the evening." },
        { t: "Arrive", d: "Drop-off right at your destination in Rome, with any agreed stops along the way." },
      ],
      sections: [
        { t: "The route", d: "From Milan we follow the A1 motorway through Bologna and Florence to Rome: about 575 km and 5h45 in normal conditions. On request we plan stops for breaks or intermediate appointments." },
        { t: "Why a private transfer", d: "For delegations, families with lots of luggage or travellers on non-standard schedules, a private transfer offers total flexibility: you leave when you want and arrive directly, with no changes." },
        { t: "Intermediate stops", d: "Bologna, Florence or a lunch break along the way: the service can be tailored. Mention the stops you would like in your request and we will include them in the quote." },
      ],
      faqs: [
        { q: "How long is the transfer from Milan to Rome?", a: "About 5 hours and 45 minutes (575 km) in normal conditions, excluding any agreed stops." },
        { q: "Can we make intermediate stops?", a: "Yes: on request we include stops for breaks or appointments along the route, included in the price agreed in advance." },
        { q: "Can we depart at night or at dawn?", a: "Yes, the service works by reservation at any hour: tell us your preferred time in the request form." },
        { q: "How many passengers and bags can you carry?", a: "The sedan is ideal for 1–3 passengers; the Mercedes V-Class van seats up to 7 with luggage. Tell us your needs in the request." },
      ],
      ctaTitle: "Book your transfer to Rome",
      ctaText: "Request availability and price: we reply quickly with a tailored proposal.",
    },
  },
};
